package io.github.qatra.web.locators.healing.reports;

import java.nio.file.Path;

/** Paths generated by the QATRA healing report exporter. */
public final class HealingReportArtifacts {
    private final Path textReport;
    private final Path jsonReport;
    private final Path htmlReport;
    private final Path patchSuggestions;

    public HealingReportArtifacts(Path textReport, Path jsonReport, Path htmlReport, Path patchSuggestions) {
        this.textReport = textReport;
        this.jsonReport = jsonReport;
        this.htmlReport = htmlReport;
        this.patchSuggestions = patchSuggestions;
    }

    public Path textReport() { return textReport; }
    public Path jsonReport() { return jsonReport; }
    public Path htmlReport() { return htmlReport; }
    public Path patchSuggestions() { return patchSuggestions; }
}
