package io.github.qatra.web.locators.healing.patches;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/** Collection of human-reviewable locator patch suggestions. */
public final class HealingPatchPlan {
    private final List<HealingCodePatchSuggestion> suggestions = new ArrayList<>();

    public HealingPatchPlan add(HealingCodePatchSuggestion suggestion) {
        if (suggestion != null) {
            suggestions.add(suggestion);
        }
        return this;
    }

    public List<HealingCodePatchSuggestion> suggestions() {
        return Collections.unmodifiableList(suggestions);
    }

    public boolean empty() {
        return suggestions.isEmpty();
    }

    public int size() {
        return suggestions.size();
    }

    public String toJson() {
        StringBuilder json = new StringBuilder();
        json.append("{\n  \"schema\": \"qatra-healing-patch-plan/v1\",");
        json.append("\n  \"autoApply\": false,");
        json.append("\n  \"reviewRequired\": true,");
        json.append("\n  \"suggestions\": [");
        for (int i = 0; i < suggestions.size(); i++) {
            if (i > 0) json.append(",");
            json.append("\n").append(indent(suggestions.get(i).toJson(), 4));
        }
        json.append("\n  ]\n}\n");
        return json.toString();
    }

    public String toMarkdown() {
        StringBuilder markdown = new StringBuilder();
        markdown.append("# QATRA Healing Patch Plan\n\n");
        markdown.append("These are human-reviewable locator patch suggestions generated by QATRA.\n\n");
        markdown.append("QATRA does **not** modify source code automatically. Review every suggestion before updating Page Objects.\n\n");
        if (suggestions.isEmpty()) {
            markdown.append("No patch suggestions were generated.\n");
        }
        for (HealingCodePatchSuggestion suggestion : suggestions) {
            markdown.append(suggestion.toMarkdown()).append("\n---\n\n");
        }
        return markdown.toString();
    }

    public String toUnifiedDiff() {
        StringBuilder diff = new StringBuilder();
        diff.append("# QATRA locator patch suggestions. Review manually; do not apply blindly.\n");
        for (HealingCodePatchSuggestion suggestion : suggestions) {
            diff.append(suggestion.toUnifiedDiff()).append("\n");
        }
        return diff.toString();
    }

    public String toApprovalTemplateJson() {
        StringBuilder json = new StringBuilder();
        json.append("{\n  \"schema\": \"qatra-healing-approval/v1\",");
        json.append("\n  \"instructions\": \"Change approved to true only after human review.\",");
        json.append("\n  \"approvals\": [");
        for (int i = 0; i < suggestions.size(); i++) {
            HealingCodePatchSuggestion s = suggestions.get(i);
            if (i > 0) json.append(",");
            json.append("\n    {");
            json.append("\n      \"id\": \"").append(escape(s.id())).append("\",");
            json.append("\n      \"locatorName\": \"").append(escape(s.locatorName())).append("\",");
            json.append("\n      \"oldLocator\": \"").append(escape(s.oldLocator())).append("\",");
            json.append("\n      \"newLocator\": \"").append(escape(s.newLocator())).append("\",");
            json.append("\n      \"suggestedJavaCode\": \"").append(escape(s.suggestedJavaCode())).append("\",");
            json.append("\n      \"approved\": false,");
            json.append("\n      \"reviewer\": \"\",");
            json.append("\n      \"reviewComment\": \"\"");
            json.append("\n    }");
        }
        json.append("\n  ]\n}\n");
        return json.toString();
    }

    private static String indent(String text, int spaces) {
        String prefix = " ".repeat(Math.max(0, spaces));
        return prefix + text.replace("\n", "\n" + prefix);
    }

    private static String escape(String value) {
        if (value == null) return "";
        return value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "");
    }
}
