package io.github.qatra.web.locators;

import io.github.qatra.web.locators.advisor.LocatorAdvisorReport;
import io.github.qatra.web.locators.advisor.ProactiveLocatorQualityAdvisor;
import org.openqa.selenium.By;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Heuristic locator quality advisor.
 *
 * <p>This does not replace human review; it gives fast feedback for common locator risks
 * such as absolute XPath, dynamic CSS classes, brittle indexes, and missing stable test ids.</p>
 */
public final class LocatorQualityAdvisor {

    private LocatorQualityAdvisor() {
    }

    public static LocatorQualityReport analyze(By locator) {
        String raw = String.valueOf(locator);
        String lower = raw.toLowerCase(Locale.ROOT);
        int score = 75;
        List<String> reasons = new ArrayList<>();
        List<String> recommendations = new ArrayList<>();

        if (lower.contains("by.id")) {
            score += 15;
            reasons.add("ID locator is usually stable when the value is generated intentionally.");
        }
        if (lower.contains("data-testid") || lower.contains("data-test") || lower.contains("data-qa")) {
            score += 20;
            reasons.add("Uses a test-specific attribute.");
        }
        if (lower.contains("by.xpath: /html") || lower.contains("xpath: /html") || lower.contains("/body/")) {
            score -= 45;
            reasons.add("Absolute XPath is fragile and tightly coupled to page structure.");
            recommendations.add("Prefer data-testid, stable id, accessible role, or a short relative XPath.");
        }
        if (lower.contains("[1]") || lower.contains("[2]") || lower.contains("nth-child")) {
            score -= 20;
            reasons.add("Index-based locators are likely to break when layout changes.");
            recommendations.add("Anchor the locator to stable text, label, or data-testid.");
        }
        if (lower.contains("class name") || lower.contains("by.classname")) {
            score -= 10;
            reasons.add("Class-name locators can be risky when CSS is generated by the UI framework.");
            recommendations.add("Use a semantic attribute or a stable component-specific locator.");
        }
        if (lower.contains("contains(text()") || lower.contains("contains(.,")) {
            score -= 5;
            reasons.add("Text-based fallback can be readable, but text may change with localization.");
            recommendations.add("Use text fallback together with a stable primary locator.");
        }
        if (lower.matches(".*(css selector|xpath).*(_ngcontent|ng-|mat-|css-[a-z0-9]|jss[0-9]|Mui[A-Za-z0-9_-]*-[0-9]).*")) {
            score -= 25;
            reasons.add("Locator appears to depend on framework-generated attributes/classes.");
            recommendations.add("Ask developers to expose stable data-testid or aria-label attributes.");
        }

        score = Math.max(0, Math.min(100, score));
        LocatorRiskLevel risk = score >= 75 ? LocatorRiskLevel.LOW : score >= 45 ? LocatorRiskLevel.MEDIUM : LocatorRiskLevel.HIGH;
        if (recommendations.isEmpty()) {
            recommendations.add("Keep locator short, stable, and business-readable.");
        }
        return new LocatorQualityReport(locator, score, risk, reasons, recommendations);
    }


    /**
     * Advanced proactive advisor for richer risk analysis, reports, and quality gates.
     */
    public static LocatorAdvisorReport analyzeProactively(By locator) {
        return ProactiveLocatorQualityAdvisor.analyze(locator);
    }

    /**
     * Advanced proactive advisor for a full QatraLocator chain, including fallback candidate quality.
     */
    public static LocatorAdvisorReport analyzeProactively(QatraLocator locator) {
        return ProactiveLocatorQualityAdvisor.analyze(locator);
    }

}
